config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get "search_tag" => "searches#search_tag"
  get 'groups/create_event'
  get 'group_mails/user_mail'
  get 'books/new_index'
  get 'books/star_index'
  get 'books/serch_result'
  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get "daily_posts" => "users#daily_posts"
  end 
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end 
  
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:new, :create, :destroy]
    resources :group_mails, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :tag, presence: true
  validates :star, presence: true
  validates :body, length: {in: 2...201}
  
  is_impressionable counter_cache: true
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_week, -> { where(created_at: Time.zone.now.all_week) } # 今週
  scope :created_last_week, -> { where(created_at: 1.week.ago.all_week) } # 先週
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) } # 6日前
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
  
  def self.looks(search, word)
    if search == "perfect_match"
     @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
     @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
     @book = Book.where("title LIKE?", "#%{word}")
    elsif search == "partial_match"
     @book = Book.where("title LIKE?", "#%{word}%")
    else
     @book = Book.all
    end 
  end 
  
  def self.looks_tag(word)
     @book = Book.where("tag LIKE?", "#{word}")
  end 
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :book
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  
  #has_many :group_users
  #has_many :users, through: :group_users
  #has_many :owner, class_name: 'User', foreign_key: 'owner_id'
  has_one_attached :image
  
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  
  has_many :users, through: :group_users, source: :user
  
  has_many :group_mails, dependent: :destroy
  
  validates :name,length: {in: 2...21},  uniqueness: true
  validates :introduction, length: {maximum:50}
   
    def get_image
    (image.attached?) ? image : 'no_image.jpg'
    end
   
    def join_group(user_id)
    group_users.create(user_id: user_id)
   end 
   
   def leave_group(user_id)
    group_users.destroy(user_id: user_id).destroy
   end 
   
   def belongs?(user)
    group_users.exists?(user_id: user.id)
   end 
   
   def member?(user_id)
    group_users.include?(user_id)
   end 
   
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
  
  validates :title, presence: true
  validates :body, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
 has_many :user_rooms
 has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_image
   has_many :books, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   has_many :followings, through: :relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower
   
   has_many :posts, dependent: :destroy
   has_many :sends, dependent: :destroy
   
   has_many :user_rooms
   has_many :chats
   has_many :rooms, through: :user_rooms
   
   #has_many :group_users
   #has_many :groups, through: :group_users
   #has_many :owners, class_name: 'Group', foreign_key: 'owner_id', dependent: :destroy
   
   has_many :group_users, dependent: :destroy
   
   validates :name,length: {in: 2...21},  uniqueness: true
   validates :introduction, length: {maximum:50}
   
   def get_profile_image(width, height)
        unless profile_image.attached?
         file_path = Rails.root.join('app/assets/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
       profile_image.variant(resize_to_limit: [width, height]).processed
   end
   
   def follow(user_id)
    relationships.create(followed_id: user_id)
   end 
   
   def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
   end 
   
   def following?(user)
    followings.include?(user)
   end 
   
   def self.looks(search, word)
    if search == "perfect_match"
     @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
     @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
     @user = User.where("name LIKE?", "#%{word}")
    elsif search == "partial_match"
     @user = User.where("name LIKE?", "#%{word}%")
    else
     @user = User.all
    end 
   end 
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.save
    
    redirect_to groups_path
  end 

  def index
    @groups = Group.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = current_user
    @book = Book.new
    @group = Group.find(params[:id])
    @group_mail = GroupMail.new
  end

  def edit
    @group = Group.find(params[:id])
    if @group.owner_id != current_user.id
      redirect_to groups_path
    end 
  end 
  
  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end 
  
  def create_event
    @group_mail = GroupMail.new
  end 
  
  private
  def group_params
    params.require(:group).permit(:name,:introduction,:image)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_mails_helper.rb
module GroupMailsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/groups/_group_link.html.erb
<%= link_to "グループを作成する", new_group_path %>
<span>|</span>
<%= link_to "グループ一覧", groups_path %>

app/views/groups/create_event.html.erb
 <%= form_with model: [@group, @group_mail] do |f| %>
       <div class="form-group">
        <label for="group_mail_title">Title</label>
        <%= f.text_field :title,class: "form-control group_mail_title" %>
       </div>
       <div class="form-group">
        <label for="group_mail_body">Content</label>
         <%= f.text_area :body, class: "form-control group_mail_body" %>
       </div>
        <div class="form-group">
          <input type="submit" name="commit" value="送信" class="btn btn-success" >
        </div>
       
  <% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <%= form_with model: @group do |f| %>
        <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name,class: 'form-control user_name' %>
        </div>
        
        <div class="form-group">
          <label>Introdction</label>
          <%= f.text_area :introduction, class: "form-control user_introduction" %>
        </div>
        
        <div class="form-group">
          <label>Image</label><br>
          <%= f.file_field :image, placeholder: "グループ画像", accept: "image/*" %>
        </div>
        
        <div class="form-group">
          <input type="submit" name="commit" value="Update Group" class="btn btn-secondary">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <%= render "searches/search" %>
    <div class="row">
      <div class="col-md-3">
        <%= render "users/user_info", user: @user %>
        <%= render "books/form", book: @book %>
      </div>
      
      <div class="col-md-8 offset-md-1">
        <h2>Groups</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー数</th>
            </tr>
          </thead>
          
          <% @groups.each do |group| %>
          <tbody>
            <tr>
              <td><%= image_tag group.get_image, size: '100x100'  %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.group_users.count %></td>
             
              <% if group.owner_id == current_user.id %>
                <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-sm btn-success" %></td>
              <% end %>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <h1>Create Group</h1>
      <%= form_with model: @group do |f| %>
        <div class="form-group">
          <label>グループ名</label>
          <%= f.text_field :name, class: "form-control group_name" %>
        </div>
        
        <div class="form-group">
          <label>紹介文</label>
          <%= f.text_area :introduction, class: "form-control group_introduction" %>
        </div>
        
        <div class="form-group">
          <label>グループ画像</label><br>
          <%= f.file_field :image, placeholder: "ファイルを選択", accept: "image/*" %>
        </div>
        
        <div class="form-group">
        <input type="submit" name="commit" value="Create Group" class="btn btn-success">
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <%= render "searches/search" %>
    <div class="row">
      <div class="col-md-3">
        <%= render "users/user_info", user: @user %>
        <%= render "books/form", book: @book %>
      </div>
      
      <div class="col-md-8 offset-md-1">
        <h2>Group Detail</h2>
        <span><%= link_to "Back", groups_path %></span>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th><p> グループ名 </p></th>
              <th><p>紹介文</p></th>
              <th><p>メンバー</p></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= image_tag @group.get_image, size: '100x100' %></td>
              <td><%= @group.name %></td>
              <td><%= @group.introduction %></td>
               <td>
                <% @group.users.each do |user| %>
                 <li style="list-style: none;"><%= user.name %></li>
                <% end %>
                </td>
                <% if @group.owner_id == current_user.id %>
                  <td><%= link_to "Edit", edit_group_path(@group), class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "Event List",group_group_mails_path(@group), class: "btn btn-sm btn-info" %></td>
                <% else %>
                  <% unless @group.belongs?(current_user) %>
                    <td class="join-btn">
                      <%= render "group_users/join-btn", group: @group %>
                    </td>
                  <% else %>
                    <td class="leave-btn">
                      <%= render "group_users/leave-btn", group: @group %>
                    </td>
                  <% end %>
              <% end %>
              
            </tr>
          </tbody>
        </table>
        <% if @group.owner_id == current_user.id %>
        <h2>Create Event</h2>
           <%= form_with model: [@group, @group_mail] do |f| %>
          <div class="form-group">
            <label for="group_mail_title">Title</label>
              <%= f.text_field :title,class: "form-control group_mail_title" %>
            </div>
          <div class="form-group">
            <label for="group_mail_body">Content</label>
             <%= f.text_area :body, class: "form-control group_mail_body" %>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="送信" class="btn btn-success" >
            </div>
        <% end %>
       
  <% end %>
      </div>
    </div>
  </div>