config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get "search_tag" => "searches#search_tag"
  get 'groups/create_event'
  get 'group_mails/user_mail'
  get 'books/new_index'
  get 'books/star_index'
  get 'books/serch_result'
  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get "daily_posts" => "users#daily_posts"
  end 
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end 
  
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:new, :create, :destroy]
    resources :group_mails, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :tag, presence: true
  validates :star, presence: true
  validates :body, length: {in: 2...201}
  
  is_impressionable counter_cache: true
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_week, -> { where(created_at: Time.zone.now.all_week) } # 今週
  scope :created_last_week, -> { where(created_at: 1.week.ago.all_week) } # 先週
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) } # 6日前
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
  
  def self.looks(search, word)
    if search == "perfect_match"
     @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
     @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
     @book = Book.where("title LIKE?", "#%{word}")
    elsif search == "partial_match"
     @book = Book.where("title LIKE?", "#%{word}%")
    else
     @book = Book.all
    end 
  end 
  
  def self.looks_tag(word)
     @book = Book.where("tag LIKE?", "#{word}")
  end 
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :book
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  
  #has_many :group_users
  #has_many :users, through: :group_users
  #has_many :owner, class_name: 'User', foreign_key: 'owner_id'
  has_one_attached :image
  
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  
  has_many :users, through: :group_users, source: :user
  
  has_many :group_mails, dependent: :destroy
  
  validates :name,length: {in: 2...21},  uniqueness: true
  validates :introduction, length: {maximum:50}
   
    def get_image
    (image.attached?) ? image : 'no_image.jpg'
    end
   
    def join_group(user_id)
    group_users.create(user_id: user_id)
   end 
   
   def leave_group(user_id)
    group_users.destroy(user_id: user_id).destroy
   end 
   
   def belongs?(user)
    group_users.exists?(user_id: user.id)
   end 
   
   def member?(user_id)
    group_users.include?(user_id)
   end 
   
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
  
  validates :title, presence: true
  validates :body, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
 has_many :user_rooms
 has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_image
   has_many :books, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   has_many :followings, through: :relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower
   
   has_many :posts, dependent: :destroy
   has_many :sends, dependent: :destroy
   
   has_many :user_rooms
   has_many :chats
   has_many :rooms, through: :user_rooms
   
   #has_many :group_users
   #has_many :groups, through: :group_users
   #has_many :owners, class_name: 'Group', foreign_key: 'owner_id', dependent: :destroy
   
   has_many :group_users, dependent: :destroy
   
   validates :name,length: {in: 2...21},  uniqueness: true
   validates :introduction, length: {maximum:50}
   
   def get_profile_image(width, height)
        unless profile_image.attached?
         file_path = Rails.root.join('app/assets/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
       profile_image.variant(resize_to_limit: [width, height]).processed
   end
   
   def follow(user_id)
    relationships.create(followed_id: user_id)
   end 
   
   def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
   end 
   
   def following?(user)
    followings.include?(user)
   end 
   
   def self.looks(search, word)
    if search == "perfect_match"
     @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
     @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
     @user = User.where("name LIKE?", "#%{word}")
    elsif search == "partial_match"
     @user = User.where("name LIKE?", "#%{word}%")
    else
     @user = User.all
    end 
   end 
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  end 

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
  end 
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else 
      render :edit
    end 
  end 
    
  def daily_posts
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end
  
  
  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_user_info.html.erb
<p><h2>User info</h2>
  <%= link_to  group_mails_user_mail_path do %>
    <i class="far fa-envelope"></i>
  <% end %>
  </p>
  <%= image_tag @user.get_profile_image(100,100) %>
  
<table class="table">
  <tbody>
    <tr>
      <th><p>name</p></th>
      <th><p><%= @user.name %></p></th>
    </tr>
    <tr>
      <th><p>introduction</p></th>
      <th><p> <%= @user.introduction %></p></th>
    </tr>
    <tr>
      <th>follow</th>
      <td><%= link_to @user.followings.count, user_followings_path(@user) %></td>
    </tr>
    <tr>
      <th>followers</th>
      <td>
        <%= link_to user.followers.count, user_followers_path(user) %>
      </td>
    </tr>
     
  </tbody>
</table>
    <div class="row">
      <div class="col-md-10 mx-auto">
        <% unless @user == current_user %>
          <% if current_user.following?(@user) %>
             <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-sm btn-block btn-danger" %>
          <% else %>
              <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-sm btn-block btn-success" %>
          <% end %>
          <% end %>
          <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
            <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
          <% end %>
      </div>
    </div>
<%= link_to  edit_user_path(@user),class: "btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %> errors prohibited this obj from being saved:
         <ul>
          <% @user.errors.full_messages.each do |message| %>
           <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name,class: 'form-control user_name' %>
      </div>
      
      <div class="form-group">
        <label>Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
      
      <div class="form-group">
        <label>Introdction</label>
        <%= f.text_area :introduction, class: "form-control user_introduction" %>
      </div>
      
      <div class="form-group">
        <input type="submit" name="commit" value="Update User" class="btn btn-secondary">
      </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= render "searches/search" %>
    <div class="row">
      <div class="col-md-3">
        <%= render "user_info", user: @user %>
        <%= render "books/form", book: @book %>
      </div>
      
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <%= render "groups/group_link" %>
        <table class="table">
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
          </tr>
          <tr>
            <% @users.each do |user| %>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
              <td class="follow_btn">
                <%= render "relationships/follow_btn", user: user %>
              </td>
              <td>
                <%= link_to user.followings.count, user_followings_path(user) %>
              </td>
              <td>
                <%= link_to user.followers.count, user_followers_path(user) %>
              </td>
          </tr>
            <% end %>
        </table>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<main>
<div class="container px-5 px-sm-0">
 <%= render "searches/search" %>
  <div class="row">
   <div class="col-md-3">
     <%= render 'user_info', user: @user%>
     <%= render 'books/form', book: @book %>
   </div>
   <div class="col-md-8 offset-md-1">
    <table class="table">
     <h2>Books</h2>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
       <% @books.each do |book| %>
       <% if book.user_id == @user.id %>
       <tr>
            <td><%= link_to (image_tag book.user.get_profile_image(100,100)), user_path(book.user_id) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        <% end %> 
       </table>
       
         <%= render 'daily_posts_form', user: @user %>

    </div>
  </div>
</div>
</main>