config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get "search_tag" => "searches#search_tag"
  get 'groups/create_event'
  get 'group_mails/user_mail'
  get 'books/new_index'
  get 'books/star_index'
  get 'books/serch_result'
  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get "daily_posts" => "users#daily_posts"
  end 
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end 
  
  resources :groups, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :group_users, only: [:new, :create, :destroy]
    resources :group_mails, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :tag, presence: true
  validates :star, presence: true
  validates :body, length: {in: 2...201}
  
  is_impressionable counter_cache: true
  
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_week, -> { where(created_at: Time.zone.now.all_week) } # 今週
  scope :created_last_week, -> { where(created_at: 1.week.ago.all_week) } # 先週
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) } # 6日前
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
  
  def self.looks(search, word)
    if search == "perfect_match"
     @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
     @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
     @book = Book.where("title LIKE?", "#%{word}")
    elsif search == "partial_match"
     @book = Book.where("title LIKE?", "#%{word}%")
    else
     @book = Book.all
    end 
  end 
  
  def self.looks_tag(word)
     @book = Book.where("tag LIKE?", "#{word}")
  end 
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :book
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  
  #has_many :group_users
  #has_many :users, through: :group_users
  #has_many :owner, class_name: 'User', foreign_key: 'owner_id'
  has_one_attached :image
  
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  
  has_many :users, through: :group_users, source: :user
  
  has_many :group_mails, dependent: :destroy
  
  validates :name,length: {in: 2...21},  uniqueness: true
  validates :introduction, length: {maximum:50}
   
    def get_image
    (image.attached?) ? image : 'no_image.jpg'
    end
   
    def join_group(user_id)
    group_users.create(user_id: user_id)
   end 
   
   def leave_group(user_id)
    group_users.destroy(user_id: user_id).destroy
   end 
   
   def belongs?(user)
    group_users.exists?(user_id: user.id)
   end 
   
   def member?(user_id)
    group_users.include?(user_id)
   end 
   
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
  
  validates :title, presence: true
  validates :body, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
 has_many :user_rooms
 has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one_attached :profile_image
   has_many :books, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   
   has_many :followings, through: :relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower
   
   has_many :posts, dependent: :destroy
   has_many :sends, dependent: :destroy
   
   has_many :user_rooms
   has_many :chats
   has_many :rooms, through: :user_rooms
   
   #has_many :group_users
   #has_many :groups, through: :group_users
   #has_many :owners, class_name: 'Group', foreign_key: 'owner_id', dependent: :destroy
   
   has_many :group_users, dependent: :destroy
   
   validates :name,length: {in: 2...21},  uniqueness: true
   validates :introduction, length: {maximum:50}
   
   def get_profile_image(width, height)
        unless profile_image.attached?
         file_path = Rails.root.join('app/assets/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
       profile_image.variant(resize_to_limit: [width, height]).processed
   end
   
   def follow(user_id)
    relationships.create(followed_id: user_id)
   end 
   
   def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
   end 
   
   def following?(user)
    followings.include?(user)
   end 
   
   def self.looks(search, word)
    if search == "perfect_match"
     @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
     @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
     @user = User.where("name LIKE?", "#%{word}")
    elsif search == "partial_match"
     @user = User.where("name LIKE?", "#%{word}%")
    else
     @user = User.all
    end 
   end 
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = (params[:range])
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end 
  end 
  
  def search_tag
    @books = Book.looks_tag(params[:word])
    @user = current_user
    @book = Book.new
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'],['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
          <td>
            <%= render "relationships/follow_btn", user: user %>
          </td>
          <td>
            <%= link_to user.followings.count, user_followings_path(user) %>
          </td>
          <td>
            <%= link_to user.followers.count, user_followers_path(user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
           <td><%= link_to "#{book.book_comments.count}Comments", book_path(book) %></td>
          <% if book.favorited_by?(current_user) %>
           <p>
             <td><%= link_to book_favorites_path(book), method: :delete do %>
               <%= book.favorites.count %>:♥</td>
               <% end %>
           </p>
          <% else %>
           <p>
             <td><%= link_to book_favorites_path(book), method: :post do %>
               <%= book.favorites.count %>:♡</td>
             <% end %>
           </p>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/searches/search_tag.html.erb
<div class="container">
  <%= render "searches/search" %>
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/user_info', user: @user %>
        <%= render 'books/form', book: @book %>
      </div>
       <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= render 'books/index_form' %>
        <div class="index">
          <table class="table">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th>Comments</th>
            <th>Rate</th>
            </tr>
            <%= render 'books/index', books: @books %>
          </table>
        </div>
      </div>
    </div>
</div>